apiVersion: apps.kubeblocks.io/v1alpha1
kind: OpsRequest
metadata:
  name: polardb-pg-switchover
spec:
  clusterName: polardb-pg
  type: Switchover
  switchover:
    - componentName: postgresql
      instanceName: '*'
