apiVersion: apps.kubeblocks.io/v1alpha1
kind: Cluster
metadata:
  name: polardb-mongo-kb08-restore-long-v1
  namespace: polardb-kb08-e2e
spec:
  clusterDefinitionRef: polardb-mongo-compat-kb08
  terminationPolicy: Delete
  affinity:
    podAntiAffinity: Preferred
    topologyKeys:
      - kubernetes.io/hostname
    tenancy: SharedNode
  componentSpecs:
    - name: documentdb
      componentDef: polardb-mongo-docdb
      replicas: 1
      resources:
        requests:
          cpu: 200m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 1Gi
      volumeClaimTemplates:
        - name: data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 2Gi
    - name: ferretdb
      componentDef: polardb-mongo-ferret
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
