apiVersion: apps.kubeblocks.io/v1alpha1
kind: OpsRequest
metadata:
  name: polardb-stack-switchover
  namespace: polardb-stack-demo
spec:
  clusterName: polardb-stack-demo
  type: Custom
  timeoutSeconds: 1200
  custom:
    opsDefinitionName: polardb-pg-stack-switchover
    serviceAccountName: polardb-pg-stack-ops
    components:
      - componentName: control
        parameters:
          - name: TARGET_INSTANCE
            value: REPLACE_RO_INSTANCE_ID
