apiVersion: apps.kubeblocks.io/v1alpha1
kind: OpsRequest
metadata:
  name: polardb-pg-backup
  namespace: kb-polardb-pg
spec:
  clusterName: polardb-pg
  type: Backup
  backup:
    backupName: polardb-pg-ha-drill-backup
    backupMethod: pg-basebackup
    deletionPolicy: Retain
    retentionPeriod: 168h
