apiVersion: apps.kubeblocks.io/v1alpha1
kind: OpsRequest
metadata:
  name: polardb-pg-switchover-auto
  namespace: kb-polardb-pg
spec:
  clusterName: polardb-pg
  type: Switchover
  switchover:
  - componentName: postgresql
    instanceName: "*"
