apiVersion: v1
kind: Namespace
metadata:
  name: polardb-pg-real
---
apiVersion: apps.kubeblocks.io/v1alpha1
kind: Cluster
metadata:
  name: polardb-pg-real
  namespace: polardb-pg-real
spec:
  terminationPolicy: Delete
  componentSpecs:
    - name: polardb
      componentDef: polardb-pg-local-v2
      replicas: 1
      disableExporter: true
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: "2"
          memory: 4Gi
      volumeClaimTemplates:
        - name: data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
