apiVersion: apps.kubeblocks.io/v1alpha1
kind: ComponentVersion
metadata:
  name: {{ include "polardbPostgresql.componentResourceName" (dict "suffix" "version" "Values" .Values) }}
  annotations:
    componentversion.kubeblocks.io/compatible-definitions: {{ include "polardbPostgresql.componentDefinitionName" . }}
    helm.sh/resource-policy: keep
  labels:
    {{ include "polardbPostgresql.componentDefinitionName" . }}: {{ include "polardbPostgresql.componentDefinitionName" . }}
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  compatibilityRules:
  - compDefs:
    - {{ include "polardbPostgresql.componentDefinitionName" . }}
    releases:
    - 12.15.0
  releases:
  - name: 12.15.0
    serviceVersion: 12.15.0
    images:
      pg-init-container: {{ include "postgresql.image.major12.minor150" . }}
      postgresql: {{ include "postgresql.image.major12.minor150" . }}
      pgbouncer: {{ include "pgbouncer.image" . }}
