apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "polardbPostgresql.componentResourceName" (dict "suffix" "pgbouncer-configuration" "Values" .Values) }}
  annotations:
    helm.sh/resource-policy: keep
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
data:
  pgbouncer.ini: |-
    {{- .Files.Get "config/pgbouncer-ini.tpl" | nindent 4 }}
