name: PULL-REQUEST-USER-INTERACT

on:
  pull_request_target:
    types: [ edited, opened ]

permissions:
  issues: write
  pull-requests: write

env:
  GITHUB_TOKEN: ${{ github.token }}
  REVIEWERS: 'realzyy,fireworm2002'
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  get-issue-label:
    name: GET PR Issue Label
    runs-on: ubuntu-latest
    steps:
      - id: issue
        name: Get linked issue labels
        run: |
          gh api graphql -f query='
            query($org: String!,$repo: String!,$number: Int!){
              repository(owner: $org, name: $repo) {
                pullRequest(number: $number) {
                  id
                  closingIssuesReferences (first: 10) {
                    edges {
                      node {
                        number
                        labels (first: 10)  { edges{ node {name}} }
                      }
                    }
                  }
                }
              }
            }' -f org="$GITHUB_REPOSITORY_OWNER" -f repo="${GITHUB_REPOSITORY#*/}" -F number="$PR_NUMBER" > label_data.json
          has_interaction_label="$(jq -r '[.data.repository.pullRequest.closingIssuesReferences.edges[].node.labels.edges[].node.name | select(. == "area/user-interaction")] | length > 0' label_data.json)"
          echo "has_interaction_label=$has_interaction_label" >> "$GITHUB_OUTPUT"

      - name: Label and request reviewers
        if: steps.issue.outputs.has_interaction_label == 'true'
        run: |
          gh api --method POST "repos/$GITHUB_REPOSITORY/issues/$PR_NUMBER/labels" -f 'labels[]=area/user-interaction'
          gh api --method POST "repos/$GITHUB_REPOSITORY/pulls/$PR_NUMBER/requested_reviewers" \
            -f 'reviewers[]=realzyy' \
            -f 'reviewers[]=fireworm2002'
